// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: smartContract.proto

package smartcontract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	ProposeContract(ctx context.Context, in *ProposeContractRequest, opts ...grpc.CallOption) (*ProposeContractResponse, error)
	ValidateContract(ctx context.Context, in *ValidateContractRequest, opts ...grpc.CallOption) (*ValidateContractResponse, error)
	AchieveConsensus(ctx context.Context, in *ConsensusRequest, opts ...grpc.CallOption) (*ConsensusResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) ProposeContract(ctx context.Context, in *ProposeContractRequest, opts ...grpc.CallOption) (*ProposeContractResponse, error) {
	out := new(ProposeContractResponse)
	err := c.cc.Invoke(ctx, "/proto.NodeService/ProposeContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ValidateContract(ctx context.Context, in *ValidateContractRequest, opts ...grpc.CallOption) (*ValidateContractResponse, error) {
	out := new(ValidateContractResponse)
	err := c.cc.Invoke(ctx, "/proto.NodeService/ValidateContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AchieveConsensus(ctx context.Context, in *ConsensusRequest, opts ...grpc.CallOption) (*ConsensusResponse, error) {
	out := new(ConsensusResponse)
	err := c.cc.Invoke(ctx, "/proto.NodeService/AchieveConsensus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility
type NodeServiceServer interface {
	ProposeContract(context.Context, *ProposeContractRequest) (*ProposeContractResponse, error)
	ValidateContract(context.Context, *ValidateContractRequest) (*ValidateContractResponse, error)
	AchieveConsensus(context.Context, *ConsensusRequest) (*ConsensusResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (UnimplementedNodeServiceServer) ProposeContract(context.Context, *ProposeContractRequest) (*ProposeContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeContract not implemented")
}
func (UnimplementedNodeServiceServer) ValidateContract(context.Context, *ValidateContractRequest) (*ValidateContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateContract not implemented")
}
func (UnimplementedNodeServiceServer) AchieveConsensus(context.Context, *ConsensusRequest) (*ConsensusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AchieveConsensus not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_ProposeContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ProposeContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NodeService/ProposeContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ProposeContract(ctx, req.(*ProposeContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ValidateContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ValidateContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NodeService/ValidateContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ValidateContract(ctx, req.(*ValidateContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AchieveConsensus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsensusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AchieveConsensus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NodeService/AchieveConsensus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AchieveConsensus(ctx, req.(*ConsensusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeContract",
			Handler:    _NodeService_ProposeContract_Handler,
		},
		{
			MethodName: "ValidateContract",
			Handler:    _NodeService_ValidateContract_Handler,
		},
		{
			MethodName: "AchieveConsensus",
			Handler:    _NodeService_AchieveConsensus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smartContract.proto",
}
